server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/report?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: perfect2001

  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
      show-sql: true
      format-sql: true
      type: info
      use-sql-comments: true
      properties:
        hibernate.use_sql_comments: true
        hibernate.format_sql: true
  servlet:
    multipart:

      max-file-size: 10MB
      max-request-size: 10MB

  tomcat:
    max-swallow-size: 100MB
springdoc:
  show-actuator: true
  paths-to-match: /**
  packages-to-scan: com.example.report

management:
  endpoint:
    health:
      show-details: ALWAYS
    endpoints:
      web:
        exposure:
          include: "*"

logging:
  level:
    org.springframework: INFO
    design.boilerplate.springboot: INFO

## FIXME : Customize JWT token and Swagger information for your application

jwt:
  secretKey: secret
  issuer: perfect.makuwerere@students.uz.ac.zw
  expirationMinute: 10

swagger:
  contact-name: Perfect Makuwerere & Douglas Nyabasa
  contact-mail: perfect.makuwerere@students.uz.ac.zw
  contact-url:
  app-name: Reports-Capstone-Project
  app-description: "Lets Build Stuff"
  app-version: 2.0.0
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0
